#!/bin/sh

set -e

if [ "$1" = "configure" ] &&  [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
  systemctl is-active fanctl.service && systemctl restart fanctl.service || true
fi
